<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_crud</name>
   <tag></tag>
   <elementGuidId>3bc72cbd-5c53-4c12-807e-a9094770108d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.border.p-2.mr-2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=textbox</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e9c221c5-f26d-4324-90e0-3dcf55d255be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>257eb793-623b-4833-aa3f-20ae0bd2c3d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>border p-2 mr-2</value>
      <webElementGuid>938d6e40-6e05-4dbd-b7ef-a7421cf2fdd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;geist_6feb203d-module__8DQF1a__variable geist_mono_c7d183a-module__ZW1U4G__variable antialiased&quot;]/div[@class=&quot;container mx-auto p-4&quot;]/div[@class=&quot;mb-4&quot;]/input[@class=&quot;border p-2 mr-2&quot;]</value>
      <webElementGuid>2a809f95-648b-4d71-9acf-7852daa41b7e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='']</value>
      <webElementGuid>2d36a251-45db-4222-b98f-7ce3f0e3a6ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>48c56487-771a-41ca-a63d-264ebc7ae47c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>62400fc4-77ab-4465-8eac-61e74fc2074b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
